name: Build King Client

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      minecraft-version:
        description: 'Wersja Minecraft'
        required: true
        default: '1.20.4'
        type: choice
        options:
          - '1.8.9'
          - '1.19.4'
          - '1.20.1'
          - '1.20.4'
          - '1.21.1'
          - '1.22.1'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: 8.5
    
    - name: Build with Gradle
      run: ./gradlew build -PmcVersion=${{ github.event.inputs.minecraft-version }}
    
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: KingClient-${{ github.event.inputs.minecraft-version }}
        path: build/libs/KingClient-*.jar